//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _02_64x64 {
            get {
                object obj = ResourceManager.GetObject("_02_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _119 {
            get {
                object obj = ResourceManager.GetObject("_119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12 {
            get {
                object obj = ResourceManager.GetObject("12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _15 {
            get {
                object obj = ResourceManager.GetObject("15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _19 {
            get {
                object obj = ResourceManager.GetObject("_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _31 {
            get {
                object obj = ResourceManager.GetObject("31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _36 {
            get {
                object obj = ResourceManager.GetObject("36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _50 {
            get {
                object obj = ResourceManager.GetObject("50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Boolean_False {
            get {
                return ResourceManager.GetString("Boolean_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Boolean_True {
            get {
                return ResourceManager.GetString("Boolean_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of invalid format (expected: Boolean).
        /// </summary>
        internal static string Conversion_BadFormatOfBooleanValue {
            get {
                return ResourceManager.GetString("Conversion_BadFormatOfBooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of invalid format (expected: Currency).
        /// </summary>
        internal static string Conversion_BadFormatOfCurrencyValue {
            get {
                return ResourceManager.GetString("Conversion_BadFormatOfCurrencyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of invalid format (expected: Date).
        /// </summary>
        internal static string Conversion_BadFormatOfDateTimeValue {
            get {
                return ResourceManager.GetString("Conversion_BadFormatOfDateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of invalid format (expected: integer or floating-point Number).
        /// </summary>
        internal static string Conversion_BadFormatOfNumericValue {
            get {
                return ResourceManager.GetString("Conversion_BadFormatOfNumericValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is of invalid format (expected: Percent).
        /// </summary>
        internal static string Conversion_BadFormatOfPercentValue {
            get {
                return ResourceManager.GetString("Conversion_BadFormatOfPercentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import from Excel....
        /// </summary>
        internal static string Menu_Branch_ImportFromExcel {
            get {
                return ResourceManager.GetString("Menu_Branch_ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;boolean value.
        /// </summary>
        internal static string New_ValueBoolean {
            get {
                return ResourceManager.GetString("New_ValueBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;currency value.
        /// </summary>
        internal static string New_ValueCurrency {
            get {
                return ResourceManager.GetString("New_ValueCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;date/time value.
        /// </summary>
        internal static string New_ValueDateTime {
            get {
                return ResourceManager.GetString("New_ValueDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;numeric value.
        /// </summary>
        internal static string New_ValueNumeric {
            get {
                return ResourceManager.GetString("New_ValueNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;percent value.
        /// </summary>
        internal static string New_ValuePercent {
            get {
                return ResourceManager.GetString("New_ValuePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New &amp;string value.
        /// </summary>
        internal static string New_ValueString {
            get {
                return ResourceManager.GetString("New_ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигатор сценария - Выберите исходное значение или формулу.
        /// </summary>
        internal static string ScenarionBrowser_SelectBranch {
            get {
                return ResourceManager.GetString("ScenarionBrowser_SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навигатор сценария - Выберите узел в дереве.
        /// </summary>
        internal static string ScenarionBrowser_SelectNode {
            get {
                return ResourceManager.GetString("ScenarionBrowser_SelectNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column header &apos;{0}&apos; has an invalid format. Column type is either not specified or invalid. List of supported types: [{1}]..
        /// </summary>
        internal static string TableImport_BadFormatOfColumnHeader {
            get {
                return ResourceManager.GetString("TableImport_BadFormatOfColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text specified is not a valid tab-delimited table: no data columns can be detected..
        /// </summary>
        internal static string TableImport_BadNumberOfColumns {
            get {
                return ResourceManager.GetString("TableImport_BadNumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text specified is not a valid tab-delimited table: no data rows can be detected..
        /// </summary>
        internal static string TableImport_BadNumberOfLines {
            get {
                return ResourceManager.GetString("TableImport_BadNumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text specified is not a valid tab-delimited table: the row &apos;{0}&apos; has {1} data columns which is different from the length {2} of the header row..
        /// </summary>
        internal static string TableImport_RowLengthDiscrepancy {
            get {
                return ResourceManager.GetString("TableImport_RowLengthDiscrepancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erroneous table format.
        /// </summary>
        internal static string TableImport_Title {
            get {
                return ResourceManager.GetString("TableImport_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string ValueType_Boolean {
            get {
                return ResourceManager.GetString("ValueType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string ValueType_Currency {
            get {
                return ResourceManager.GetString("ValueType_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ValueType_DateTime {
            get {
                return ResourceManager.GetString("ValueType_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string ValueType_Numeric {
            get {
                return ResourceManager.GetString("ValueType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string ValueType_Percent {
            get {
                return ResourceManager.GetString("ValueType_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string ValueType_String {
            get {
                return ResourceManager.GetString("ValueType_String", resourceCulture);
            }
        }
    }
}
